import type { Material } from "@/types/student/material";
import { useQuery } from "@tanstack/react-query";

export const useStudentMaterials = () => {
  const { data: materials, isLoading } = useQuery<Material[]>({
    queryKey: ["student-materials"],
    queryFn: () => {
      // Simulate a backend call until we get the backend ready
      return new Promise((resolve) => {
        setTimeout(() => {
            const fakeMaterials: Material[] = [
              // Lecture Slides
              {
                id: 1,
                title: "Lecture 10 - Fourier Transform.pdf",
                category: "lecture",
                uploaded_at: Date.now() - 2 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 1,
                  name: "Lecture 10 - Fourier Transform.pdf",
                  type: "pdf",
                  size: "2 MB",
                  url: "",
                  uploaded_at: Date.now() - 2 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 2,
                title: "Lecture 9 - Laplace Transform.pdf",
                category: "lecture",
                uploaded_at: Date.now() - 3 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 2,
                  name: "Lecture 9 - Laplace Transform.pdf",
                  type: "pdf",
                  size: "1.8 MB",
                  url: "",
                  uploaded_at: Date.now() - 3 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 3,
                title: "Lecture 8 - Z-Transform.pdf",
                category: "lecture",
                uploaded_at: Date.now() - 7 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 3,
                  name: "Lecture 8 - Z-Transform.pdf",
                  type: "pdf",
                  size: "1.5 MB",
                  url: "",
                  uploaded_at: Date.now() - 7 * 24 * 60 * 60 * 1000,
                },
              },

              // Problem Sheets
              {
                id: 4,
                title: "Problem Sheet 5 - Solutions.pdf",
                category: "sheet",
                uploaded_at: Date.now() - 4 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 4,
                  name: "Problem Sheet 5 - Solutions.pdf",
                  type: "pdf",
                  size: "1.2 MB",
                  url: "",
                  uploaded_at: Date.now() - 4 * 24 * 60 * 60 * 1000,
                },
              },

              // IDs 5–18 (simplified like IDs 1–4)
              {
                id: 5,
                title: "Problem Sheet 5.pdf",
                category: "sheet",
                uploaded_at: Date.now() - 4 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 5,
                  name: "Problem Sheet 5.pdf",
                  type: "pdf",
                  size: "1.1 MB",
                  url: "",
                  uploaded_at: Date.now() - 4 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 6,
                title: "Problem Sheet 4 - Solutions.pdf",
                category: "sheet",
                uploaded_at: Date.now() - 7 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 6,
                  name: "Problem Sheet 4 - Solutions.pdf",
                  type: "pdf",
                  size: "1.3 MB",
                  url: "",
                  uploaded_at: Date.now() - 7 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 7,
                title: "Quiz 3 - Fall 2024.pdf",
                category: "quiz",
                uploaded_at: Date.now() - 5 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 7,
                  name: "Quiz 3 - Fall 2024.pdf",
                  type: "pdf",
                  size: "0.9 MB",
                  url: "",
                  uploaded_at: Date.now() - 5 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 8,
                title: "Quiz 2 - Fall 2024.pdf",
                category: "quiz",
                uploaded_at: Date.now() - 14 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 8,
                  name: "Quiz 2 - Fall 2024.pdf",
                  type: "pdf",
                  size: "0.8 MB",
                  url: "",
                  uploaded_at: Date.now() - 14 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 9,
                title: "Quiz 1 - Fall 2024.pdf",
                category: "quiz",
                uploaded_at: Date.now() - 21 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 9,
                  name: "Quiz 1 - Fall 2024.pdf",
                  type: "pdf",
                  size: "0.7 MB",
                  url: "",
                  uploaded_at: Date.now() - 21 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 10,
                title: "Tutorial 8 - System Analysis.pdf",
                category: "tutorial",
                uploaded_at: Date.now() - 7 * 24 * 60 * 60 * 1000,
                uploader: "TA Mahmoud",
                courseCode: "EEC-225",
                file: {
                  id: 10,
                  name: "Tutorial 8 - System Analysis.pdf",
                  type: "pdf",
                  size: "1.6 MB",
                  url: "",
                  uploaded_at: Date.now() - 7 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 11,
                title: "Tutorial 7 - Frequency Response.pdf",
                category: "tutorial",
                uploaded_at: Date.now() - 14 * 24 * 60 * 60 * 1000,
                uploader: "TA Mahmoud",
                courseCode: "EEC-225",
                file: {
                  id: 11,
                  name: "Tutorial 7 - Frequency Response.pdf",
                  type: "pdf",
                  size: "1.5 MB",
                  url: "",
                  uploaded_at: Date.now() - 14 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 12,
                title: "Tutorial 6 - Transfer Functions.pdf",
                category: "tutorial",
                uploaded_at: Date.now() - 21 * 24 * 60 * 60 * 1000,
                uploader: "TA Mahmoud",
                courseCode: "EEC-225",
                file: {
                  id: 12,
                  name: "Tutorial 6 - Transfer Functions.pdf",
                  type: "pdf",
                  size: "1.4 MB",
                  url: "",
                  uploaded_at: Date.now() - 21 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 13,
                title: "Signals and Systems - Oppenheim (Chapter 5-8).pdf",
                category: "textbook",
                uploaded_at: Date.now() - 30 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 13,
                  name: "Signals and Systems - Oppenheim (Chapter 5-8).pdf",
                  type: "pdf",
                  size: "12 MB",
                  url: "",
                  uploaded_at: Date.now() - 30 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 14,
                title: "Signals and Systems - Oppenheim (Chapter 1-4).pdf",
                category: "textbook",
                uploaded_at: Date.now() - 30 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 14,
                  name: "Signals and Systems - Oppenheim (Chapter 1-4).pdf",
                  type: "pdf",
                  size: "10 MB",
                  url: "",
                  uploaded_at: Date.now() - 30 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 15,
                title: "Signals and Systems - Solutions Manual.pdf",
                category: "textbook",
                uploaded_at: Date.now() - 30 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 15,
                  name: "Signals and Systems - Solutions Manual.pdf",
                  type: "pdf",
                  size: "8 MB",
                  url: "",
                  uploaded_at: Date.now() - 30 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 16,
                title: "Assignment 4 - Signal Processing.pdf",
                category: "assignment",
                uploaded_at: Date.now() - 6 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 16,
                  name: "Assignment 4 - Signal Processing.pdf",
                  type: "pdf",
                  size: "1.3 MB",
                  url: "",
                  uploaded_at: Date.now() - 6 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 17,
                title: "Assignment 3 - Fourier Analysis.pdf",
                category: "assignment",
                uploaded_at: Date.now() - 14 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 17,
                  name: "Assignment 3 - Fourier Analysis.pdf",
                  type: "pdf",
                  size: "1.2 MB",
                  url: "",
                  uploaded_at: Date.now() - 14 * 24 * 60 * 60 * 1000,
                },
              },
              {
                id: 18,
                title: "Assignment 2 - Time Domain Analysis.pdf",
                category: "assignment",
                uploaded_at: Date.now() - 21 * 24 * 60 * 60 * 1000,
                uploader: "Dr. Abdelghany",
                courseCode: "EEC-225",
                file: {
                  id: 18,
                  name: "Assignment 2 - Time Domain Analysis.pdf",
                  type: "pdf",
                  size: "1.2 MB",
                  url: "",
                  uploaded_at: Date.now() - 21 * 24 * 60 * 60 * 1000,
                },
              },
            ];



          resolve(fakeMaterials);
        }, 1000);
      });
    },
    initialData: [],
  });

  return {
    materials,
    isLoading,
  };
};
